[package]
name = "discord-webhook2"
version = "0.1.0"
edition = "2021"
authors = ["Adrian8115"]
readme = "README.md"
description = "Discord webhook api library"
repository = "https://github.com/Adrian8115/discord-webhook2"
license = "Apache-2.0"
keywords = ["discord", "discord-api", "webhook", "discord-webhook", "network"]
categories = ["network-programming", "api-bindings"]

[dependencies]
reqwest = { version = "0.12", features = ["json", "multipart"] }
thiserror = "1.0"
url = "2.5"
serde_json = "1"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
serde = { version = "1", features = ["derive"] }
iso8061-timestamp = "0.1"
